syntax = "proto3";

package fwpb;

option go_package = "pkg/proto;hashboard";

import "hashboard.proto";

message async_heartbeat {}

enum error_cause {
    // No error
    NONE = 0;

    // Board errors
    BOARD_OVER_CURRENT = 1;
    BOARD_OVER_VOLTAGE = 2;
    BOARD_UNDER_VOLTAGE = 3;
    BOARD_OVER_TEMPERATURE = 4;

    // ASIC errors
    ASIC_OVER_VOLTAGE = 10;
    ASIC_UNDER_VOLTAGE = 11;
    ASIC_OVER_TEMPERATURE = 12;
    ASIC_UNDER_TEMPERATURE = 13;
    ASIC_ENUMERATION = 14;
    ASIC_ECC = 15;

    // Software errors
    SOFTWARE_ERROR = 20;
    USB_ERROR = 21;

    // Unknown errors
    UNKNOWN_ERROR = 99;
}

enum voltage_domain {
    // Default, voltage domain VDD
    VDD = 0;

    // MC3 voltage domains, difference between the voltage sensors
    VDD_VDDI3 = 1;
    VDDI3_VDDI2 = 2;
    VDDI2_VDDI1 = 3;
    VDDI1 = 4;

    // MC3 Cross domain voltage limits
    VDD_VDDI1 = 5;
    VDDI3_VSS = 6;
}

message asic_error_state {
    // The ID of the ASIC
    uint32 id = 1;

    // At the time of the error, the voltage of the ASIC
    float voltage = 2;

    // At the time of the error, the temperature of the ASIC
    float temperature = 3;

    // The voltage domain for the limit violation at time of error.
    // Only valid for under/over voltage limit errors
    voltage_domain voltage_domain = 4;
}

message hashboard_error {
    // The cause of the error
    error_cause cause = 1;

    // The timestamp of the error
    uint32 timestamp = 2;

    // For ASIC errors, the state of the ASIC causing the error
    asic_error_state asic = 3;
}

message async_system_health {
    // The uptime of the system RTOS in milliseconds
    uint32 uptime = 1;

    // True if the hashrail is enabled and OK
    bool hashrail_ok = 2;

    // True if the refclocks are enabled and OK
    bool refclks_ok = 3;

    // The state of the mining state machine
    mining_state mining_state = 4;

    // Array of board temperatures in degrees Celsius
    repeated float temperatures = 5;

    // The system voltage in volts
    float voltage = 6;

    // The system current in amps
    float current = 7;

    // The system power consumption in watts
    float power = 8;

    // The number of slots the scheduler has processed
    uint32 slot_counter = 9;

    // The hashrate of the system in TH/s
    float hashrate = 10;

    // The ideal hashrate of the system in TH/s
    float hashrate_ideal = 12;  // TODO: re-order these before the next release

    // The speed of fans in RPM
    uint32 fan = 11;

    // The fan current in amps
    float fan_current = 13;

    // The fan current in watts, voltage is system voltage
    float fan_power = 14;

    // New diagnostic info available for fetching
    bool coredump_available = 15;

    // True if the disciplined clock is synchronised to server time.
    bool time_synced = 16;

    // Optional: The cause of the error if the mining state is MINING_STATE_ERROR
    repeated hashboard_error errors = 99;

    // Transient warnings (auto-clearing, sent once per occurrence)
    repeated hashboard_error warnings = 100;
}

message async_mining_nonce {
    // A unique ID for the work.
    // This is used to identify the work given by the host.
    uint32 work_id = 1;

    // The block time is a Unix epoch time when the miner found the nonce.
    // This may have been rolled to generate new work.
    uint32 nTime = 2;

    // The block version number indicates which set of block validation rules to
    // follow. This may have been rolled to generate new work.
    uint32 version = 3;

    // The nonce that was found.
    uint32 nonce = 4;
}

message asic_status {
    // The voltage of the ASIC in volts
    float voltage = 1;

    // The temperature of the ASIC in degrees Celsius
    float temperature = 2;

    // PLL frequency of the ASIC in MHz
    uint32 frequency = 3;

    // Pass rate of the ASIC in percent
    float pass_rate = 4;

    // Hashrate of the ASIC in GH/s
    float hash_rate = 5;
}

message asic_debug_status {
    // Ulink ECC (MC3 only)
    uint32 uecc0 = 1;
    uint32 uecc1 = 2;
    uint32 uecc2 = 3;

    float vddi1 = 4;
    float vddi2 = 5;
    float vddi3 = 6;
}

message async_asic_health {
    // Monotonic counter of the number slots processed by the scheduler
    uint32 slot_counter = 1;

    // Array of ASIC statuses
    repeated asic_status asics = 2;
}

message async_asic_debug_health {
    // Monotonic counter of the number slots processed by the scheduler
    uint32 slot_counter = 1;

    // Array of ASIC statuses
    repeated asic_debug_status asics = 2;
}

enum hashboard_async_message_type {
    ASYNC_NONE = 0;
    ASYNC_HEARTBEAT = 1;
    ASYNC_SYSTEM_HEALTH = 2;
    ASYNC_ASIC_HEALTH = 100;
    ASYNC_MINING_NONCE = 101;
}

message hashboard_async {
    oneof msg {
        // IMPORTANT: Each variable name must exactly match the message type.

        // System
        async_heartbeat async_heartbeat = 1;
        async_system_health async_system_health = 2;

        // Mining
        async_asic_health async_asic_health = 100;
        async_mining_nonce async_mining_nonce = 101;
        async_asic_debug_health async_asic_debug_health = 102;
    }

    // The timestamp of the message in milliseconds
    uint32 timestamp = 9999;
}
