// Code generated by MockGen. DO NOT EDIT.
// Source: cohort.go
//
// Generated by this command:
//
//	mockgen -source=cohort.go -destination=mocks/mock_cohort_store.go -package=mocks CohortStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/block/proto-fleet/server/internal/domain/cohort/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCohortStore is a mock of CohortStore interface.
type MockCohortStore struct {
	ctrl     *gomock.Controller
	recorder *MockCohortStoreMockRecorder
	isgomock struct{}
}

// MockCohortStoreMockRecorder is the mock recorder for MockCohortStore.
type MockCohortStoreMockRecorder struct {
	mock *MockCohortStore
}

// NewMockCohortStore creates a new mock instance.
func NewMockCohortStore(ctrl *gomock.Controller) *MockCohortStore {
	mock := &MockCohortStore{ctrl: ctrl}
	mock.recorder = &MockCohortStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCohortStore) EXPECT() *MockCohortStoreMockRecorder {
	return m.recorder
}

// CreateCohort mocks base method.
func (m *MockCohortStore) CreateCohort(ctx context.Context, params models.CreateCohortParams) (*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCohort", ctx, params)
	ret0, _ := ret[0].(*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCohort indicates an expected call of CreateCohort.
func (mr *MockCohortStoreMockRecorder) CreateCohort(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCohort", reflect.TypeOf((*MockCohortStore)(nil).CreateCohort), ctx, params)
}

// DeleteCohortMemberships mocks base method.
func (m *MockCohortStore) DeleteCohortMemberships(ctx context.Context, orgID, cohortID int64, deviceIdentifiers []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCohortMemberships", ctx, orgID, cohortID, deviceIdentifiers)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCohortMemberships indicates an expected call of DeleteCohortMemberships.
func (mr *MockCohortStoreMockRecorder) DeleteCohortMemberships(ctx, orgID, cohortID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCohortMemberships", reflect.TypeOf((*MockCohortStore)(nil).DeleteCohortMemberships), ctx, orgID, cohortID, deviceIdentifiers)
}

// GetCohort mocks base method.
func (m *MockCohortStore) GetCohort(ctx context.Context, orgID, cohortID int64) (*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCohort", ctx, orgID, cohortID)
	ret0, _ := ret[0].(*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCohort indicates an expected call of GetCohort.
func (mr *MockCohortStoreMockRecorder) GetCohort(ctx, orgID, cohortID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCohort", reflect.TypeOf((*MockCohortStore)(nil).GetCohort), ctx, orgID, cohortID)
}

// InsertCohortMember mocks base method.
func (m *MockCohortStore) InsertCohortMember(ctx context.Context, params models.InsertCohortMemberParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCohortMember", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertCohortMember indicates an expected call of InsertCohortMember.
func (mr *MockCohortStoreMockRecorder) InsertCohortMember(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCohortMember", reflect.TypeOf((*MockCohortStore)(nil).InsertCohortMember), ctx, params)
}

// ListActiveOwnedCohortMemberships mocks base method.
func (m *MockCohortStore) ListActiveOwnedCohortMemberships(ctx context.Context, orgID int64, deviceIdentifiers []string) ([]models.CohortDeviceOwnership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveOwnedCohortMemberships", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].([]models.CohortDeviceOwnership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveOwnedCohortMemberships indicates an expected call of ListActiveOwnedCohortMemberships.
func (mr *MockCohortStoreMockRecorder) ListActiveOwnedCohortMemberships(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveOwnedCohortMemberships", reflect.TypeOf((*MockCohortStore)(nil).ListActiveOwnedCohortMemberships), ctx, orgID, deviceIdentifiers)
}

// ListCohortDeviceOwnership mocks base method.
func (m *MockCohortStore) ListCohortDeviceOwnership(ctx context.Context, orgID int64, deviceIdentifiers []string) ([]models.CohortDeviceOwnership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCohortDeviceOwnership", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].([]models.CohortDeviceOwnership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCohortDeviceOwnership indicates an expected call of ListCohortDeviceOwnership.
func (mr *MockCohortStoreMockRecorder) ListCohortDeviceOwnership(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCohortDeviceOwnership", reflect.TypeOf((*MockCohortStore)(nil).ListCohortDeviceOwnership), ctx, orgID, deviceIdentifiers)
}

// ListCohortMembers mocks base method.
func (m *MockCohortStore) ListCohortMembers(ctx context.Context, orgID, cohortID int64) ([]models.CohortMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCohortMembers", ctx, orgID, cohortID)
	ret0, _ := ret[0].([]models.CohortMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCohortMembers indicates an expected call of ListCohortMembers.
func (mr *MockCohortStoreMockRecorder) ListCohortMembers(ctx, orgID, cohortID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCohortMembers", reflect.TypeOf((*MockCohortStore)(nil).ListCohortMembers), ctx, orgID, cohortID)
}

// ListCohorts mocks base method.
func (m *MockCohortStore) ListCohorts(ctx context.Context, params models.ListCohortsParams) (models.PagedCohorts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCohorts", ctx, params)
	ret0, _ := ret[0].(models.PagedCohorts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCohorts indicates an expected call of ListCohorts.
func (mr *MockCohortStoreMockRecorder) ListCohorts(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCohorts", reflect.TypeOf((*MockCohortStore)(nil).ListCohorts), ctx, params)
}

// ListCohortsByOwner mocks base method.
func (m *MockCohortStore) ListCohortsByOwner(ctx context.Context, params models.ListCohortsByOwnerParams) (models.PagedCohorts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCohortsByOwner", ctx, params)
	ret0, _ := ret[0].(models.PagedCohorts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCohortsByOwner indicates an expected call of ListCohortsByOwner.
func (mr *MockCohortStoreMockRecorder) ListCohortsByOwner(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCohortsByOwner", reflect.TypeOf((*MockCohortStore)(nil).ListCohortsByOwner), ctx, params)
}

// ListDefaultCohortDevices mocks base method.
func (m *MockCohortStore) ListDefaultCohortDevices(ctx context.Context, orgID int64) ([]models.DefaultCohortDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDefaultCohortDevices", ctx, orgID)
	ret0, _ := ret[0].([]models.DefaultCohortDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDefaultCohortDevices indicates an expected call of ListDefaultCohortDevices.
func (mr *MockCohortStoreMockRecorder) ListDefaultCohortDevices(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDefaultCohortDevices", reflect.TypeOf((*MockCohortStore)(nil).ListDefaultCohortDevices), ctx, orgID)
}

// ListDevices mocks base method.
func (m *MockCohortStore) ListDevices(ctx context.Context, params models.ListDevicesParams) (models.PagedCohortDevices, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDevices", ctx, params)
	ret0, _ := ret[0].(models.PagedCohortDevices)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDevices indicates an expected call of ListDevices.
func (mr *MockCohortStoreMockRecorder) ListDevices(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDevices", reflect.TypeOf((*MockCohortStore)(nil).ListDevices), ctx, params)
}

// MoveDevicesToCohort mocks base method.
func (m *MockCohortStore) MoveDevicesToCohort(ctx context.Context, params models.MembershipMutationParams) (*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveDevicesToCohort", ctx, params)
	ret0, _ := ret[0].(*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveDevicesToCohort indicates an expected call of MoveDevicesToCohort.
func (mr *MockCohortStoreMockRecorder) MoveDevicesToCohort(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveDevicesToCohort", reflect.TypeOf((*MockCohortStore)(nil).MoveDevicesToCohort), ctx, params)
}

// ReleaseCohort mocks base method.
func (m *MockCohortStore) ReleaseCohort(ctx context.Context, orgID, cohortID int64) (*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseCohort", ctx, orgID, cohortID)
	ret0, _ := ret[0].(*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseCohort indicates an expected call of ReleaseCohort.
func (mr *MockCohortStoreMockRecorder) ReleaseCohort(ctx, orgID, cohortID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseCohort", reflect.TypeOf((*MockCohortStore)(nil).ReleaseCohort), ctx, orgID, cohortID)
}

// RemoveDevicesAndGetCohort mocks base method.
func (m *MockCohortStore) RemoveDevicesAndGetCohort(ctx context.Context, params models.MembershipMutationParams) (*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDevicesAndGetCohort", ctx, params)
	ret0, _ := ret[0].(*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveDevicesAndGetCohort indicates an expected call of RemoveDevicesAndGetCohort.
func (mr *MockCohortStoreMockRecorder) RemoveDevicesAndGetCohort(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDevicesAndGetCohort", reflect.TypeOf((*MockCohortStore)(nil).RemoveDevicesAndGetCohort), ctx, params)
}

// ResolveEffectiveCohortForDevice mocks base method.
func (m *MockCohortStore) ResolveEffectiveCohortForDevice(ctx context.Context, orgID int64, deviceIdentifier string) (*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveEffectiveCohortForDevice", ctx, orgID, deviceIdentifier)
	ret0, _ := ret[0].(*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveEffectiveCohortForDevice indicates an expected call of ResolveEffectiveCohortForDevice.
func (mr *MockCohortStoreMockRecorder) ResolveEffectiveCohortForDevice(ctx, orgID, deviceIdentifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveEffectiveCohortForDevice", reflect.TypeOf((*MockCohortStore)(nil).ResolveEffectiveCohortForDevice), ctx, orgID, deviceIdentifier)
}

// SetCohortFirmwareTarget mocks base method.
func (m *MockCohortStore) SetCohortFirmwareTarget(ctx context.Context, params models.SetCohortFirmwareTargetParams) (*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCohortFirmwareTarget", ctx, params)
	ret0, _ := ret[0].(*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetCohortFirmwareTarget indicates an expected call of SetCohortFirmwareTarget.
func (mr *MockCohortStoreMockRecorder) SetCohortFirmwareTarget(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCohortFirmwareTarget", reflect.TypeOf((*MockCohortStore)(nil).SetCohortFirmwareTarget), ctx, params)
}

// SweepExpiredCohorts mocks base method.
func (m *MockCohortStore) SweepExpiredCohorts(ctx context.Context) ([]*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SweepExpiredCohorts", ctx)
	ret0, _ := ret[0].([]*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SweepExpiredCohorts indicates an expected call of SweepExpiredCohorts.
func (mr *MockCohortStoreMockRecorder) SweepExpiredCohorts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SweepExpiredCohorts", reflect.TypeOf((*MockCohortStore)(nil).SweepExpiredCohorts), ctx)
}

// UpdateCohort mocks base method.
func (m *MockCohortStore) UpdateCohort(ctx context.Context, params models.UpdateCohortParams) (*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCohort", ctx, params)
	ret0, _ := ret[0].(*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCohort indicates an expected call of UpdateCohort.
func (mr *MockCohortStoreMockRecorder) UpdateCohort(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCohort", reflect.TypeOf((*MockCohortStore)(nil).UpdateCohort), ctx, params)
}

// UpdateDefaultCohortFirmware mocks base method.
func (m *MockCohortStore) UpdateDefaultCohortFirmware(ctx context.Context, params models.UpdateCohortParams) (*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDefaultCohortFirmware", ctx, params)
	ret0, _ := ret[0].(*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDefaultCohortFirmware indicates an expected call of UpdateDefaultCohortFirmware.
func (mr *MockCohortStoreMockRecorder) UpdateDefaultCohortFirmware(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDefaultCohortFirmware", reflect.TypeOf((*MockCohortStore)(nil).UpdateDefaultCohortFirmware), ctx, params)
}

// MockCohortFirmwareEnforcementStore is a mock of CohortFirmwareEnforcementStore interface.
type MockCohortFirmwareEnforcementStore struct {
	ctrl     *gomock.Controller
	recorder *MockCohortFirmwareEnforcementStoreMockRecorder
	isgomock struct{}
}

// MockCohortFirmwareEnforcementStoreMockRecorder is the mock recorder for MockCohortFirmwareEnforcementStore.
type MockCohortFirmwareEnforcementStoreMockRecorder struct {
	mock *MockCohortFirmwareEnforcementStore
}

// NewMockCohortFirmwareEnforcementStore creates a new mock instance.
func NewMockCohortFirmwareEnforcementStore(ctrl *gomock.Controller) *MockCohortFirmwareEnforcementStore {
	mock := &MockCohortFirmwareEnforcementStore{ctrl: ctrl}
	mock.recorder = &MockCohortFirmwareEnforcementStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCohortFirmwareEnforcementStore) EXPECT() *MockCohortFirmwareEnforcementStoreMockRecorder {
	return m.recorder
}

// ClaimFirmwareDispatch mocks base method.
func (m *MockCohortFirmwareEnforcementStore) ClaimFirmwareDispatch(ctx context.Context, params models.ClaimFirmwareDispatchParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimFirmwareDispatch", ctx, params)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimFirmwareDispatch indicates an expected call of ClaimFirmwareDispatch.
func (mr *MockCohortFirmwareEnforcementStoreMockRecorder) ClaimFirmwareDispatch(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimFirmwareDispatch", reflect.TypeOf((*MockCohortFirmwareEnforcementStore)(nil).ClaimFirmwareDispatch), ctx, params)
}

// ClearMissingFirmwareTarget mocks base method.
func (m *MockCohortFirmwareEnforcementStore) ClearMissingFirmwareTarget(ctx context.Context, orgID int64, firmwareFileID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearMissingFirmwareTarget", ctx, orgID, firmwareFileID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearMissingFirmwareTarget indicates an expected call of ClearMissingFirmwareTarget.
func (mr *MockCohortFirmwareEnforcementStoreMockRecorder) ClearMissingFirmwareTarget(ctx, orgID, firmwareFileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearMissingFirmwareTarget", reflect.TypeOf((*MockCohortFirmwareEnforcementStore)(nil).ClearMissingFirmwareTarget), ctx, orgID, firmwareFileID)
}

// IsCommandBatchFinished mocks base method.
func (m *MockCohortFirmwareEnforcementStore) IsCommandBatchFinished(ctx context.Context, batchUUID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCommandBatchFinished", ctx, batchUUID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCommandBatchFinished indicates an expected call of IsCommandBatchFinished.
func (mr *MockCohortFirmwareEnforcementStoreMockRecorder) IsCommandBatchFinished(ctx, batchUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCommandBatchFinished", reflect.TypeOf((*MockCohortFirmwareEnforcementStore)(nil).IsCommandBatchFinished), ctx, batchUUID)
}

// ListFirmwareEnforcementCandidates mocks base method.
func (m *MockCohortFirmwareEnforcementStore) ListFirmwareEnforcementCandidates(ctx context.Context, orgID int64) ([]models.FirmwareEnforcementCandidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFirmwareEnforcementCandidates", ctx, orgID)
	ret0, _ := ret[0].([]models.FirmwareEnforcementCandidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFirmwareEnforcementCandidates indicates an expected call of ListFirmwareEnforcementCandidates.
func (mr *MockCohortFirmwareEnforcementStoreMockRecorder) ListFirmwareEnforcementCandidates(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFirmwareEnforcementCandidates", reflect.TypeOf((*MockCohortFirmwareEnforcementStore)(nil).ListFirmwareEnforcementCandidates), ctx, orgID)
}

// ListOrgsWithFirmwareTargets mocks base method.
func (m *MockCohortFirmwareEnforcementStore) ListOrgsWithFirmwareTargets(ctx context.Context) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrgsWithFirmwareTargets", ctx)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrgsWithFirmwareTargets indicates an expected call of ListOrgsWithFirmwareTargets.
func (mr *MockCohortFirmwareEnforcementStoreMockRecorder) ListOrgsWithFirmwareTargets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrgsWithFirmwareTargets", reflect.TypeOf((*MockCohortFirmwareEnforcementStore)(nil).ListOrgsWithFirmwareTargets), ctx)
}

// MarkFirmwareConfirmed mocks base method.
func (m *MockCohortFirmwareEnforcementStore) MarkFirmwareConfirmed(ctx context.Context, params models.MarkFirmwareConfirmedParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFirmwareConfirmed", ctx, params)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkFirmwareConfirmed indicates an expected call of MarkFirmwareConfirmed.
func (mr *MockCohortFirmwareEnforcementStoreMockRecorder) MarkFirmwareConfirmed(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFirmwareConfirmed", reflect.TypeOf((*MockCohortFirmwareEnforcementStore)(nil).MarkFirmwareConfirmed), ctx, params)
}

// MarkFirmwareDispatchFailure mocks base method.
func (m *MockCohortFirmwareEnforcementStore) MarkFirmwareDispatchFailure(ctx context.Context, params models.MarkFirmwareDispatchFailureParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFirmwareDispatchFailure", ctx, params)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkFirmwareDispatchFailure indicates an expected call of MarkFirmwareDispatchFailure.
func (mr *MockCohortFirmwareEnforcementStoreMockRecorder) MarkFirmwareDispatchFailure(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFirmwareDispatchFailure", reflect.TypeOf((*MockCohortFirmwareEnforcementStore)(nil).MarkFirmwareDispatchFailure), ctx, params)
}

// MarkFirmwareDispatchHeld mocks base method.
func (m *MockCohortFirmwareEnforcementStore) MarkFirmwareDispatchHeld(ctx context.Context, params models.MarkFirmwareDispatchHeldParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFirmwareDispatchHeld", ctx, params)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkFirmwareDispatchHeld indicates an expected call of MarkFirmwareDispatchHeld.
func (mr *MockCohortFirmwareEnforcementStoreMockRecorder) MarkFirmwareDispatchHeld(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFirmwareDispatchHeld", reflect.TypeOf((*MockCohortFirmwareEnforcementStore)(nil).MarkFirmwareDispatchHeld), ctx, params)
}

// MarkFirmwareDispatched mocks base method.
func (m *MockCohortFirmwareEnforcementStore) MarkFirmwareDispatched(ctx context.Context, params models.MarkFirmwareDispatchedParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFirmwareDispatched", ctx, params)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkFirmwareDispatched indicates an expected call of MarkFirmwareDispatched.
func (mr *MockCohortFirmwareEnforcementStoreMockRecorder) MarkFirmwareDispatched(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFirmwareDispatched", reflect.TypeOf((*MockCohortFirmwareEnforcementStore)(nil).MarkFirmwareDispatched), ctx, params)
}

// MarkFirmwareDrifted mocks base method.
func (m *MockCohortFirmwareEnforcementStore) MarkFirmwareDrifted(ctx context.Context, params models.MarkFirmwareDriftedParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFirmwareDrifted", ctx, params)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkFirmwareDrifted indicates an expected call of MarkFirmwareDrifted.
func (mr *MockCohortFirmwareEnforcementStoreMockRecorder) MarkFirmwareDrifted(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFirmwareDrifted", reflect.TypeOf((*MockCohortFirmwareEnforcementStore)(nil).MarkFirmwareDrifted), ctx, params)
}

// UpsertCohortReconcilerHeartbeat mocks base method.
func (m *MockCohortFirmwareEnforcementStore) UpsertCohortReconcilerHeartbeat(ctx context.Context, lastTickAt time.Time, lastTickUUID uuid.UUID, durationMS *int32, activeDeviceCount int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCohortReconcilerHeartbeat", ctx, lastTickAt, lastTickUUID, durationMS, activeDeviceCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCohortReconcilerHeartbeat indicates an expected call of UpsertCohortReconcilerHeartbeat.
func (mr *MockCohortFirmwareEnforcementStoreMockRecorder) UpsertCohortReconcilerHeartbeat(ctx, lastTickAt, lastTickUUID, durationMS, activeDeviceCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCohortReconcilerHeartbeat", reflect.TypeOf((*MockCohortFirmwareEnforcementStore)(nil).UpsertCohortReconcilerHeartbeat), ctx, lastTickAt, lastTickUUID, durationMS, activeDeviceCount)
}
