// Code generated by MockGen. DO NOT EDIT.
// Source: cohort.go
//
// Generated by this command:
//
//	mockgen -source=cohort.go -destination=mocks/mock_cohort_store.go -package=mocks CohortStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/block/proto-fleet/server/internal/domain/cohort/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCohortStore is a mock of CohortStore interface.
type MockCohortStore struct {
	ctrl     *gomock.Controller
	recorder *MockCohortStoreMockRecorder
	isgomock struct{}
}

// MockCohortStoreMockRecorder is the mock recorder for MockCohortStore.
type MockCohortStoreMockRecorder struct {
	mock *MockCohortStore
}

// NewMockCohortStore creates a new mock instance.
func NewMockCohortStore(ctrl *gomock.Controller) *MockCohortStore {
	mock := &MockCohortStore{ctrl: ctrl}
	mock.recorder = &MockCohortStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCohortStore) EXPECT() *MockCohortStoreMockRecorder {
	return m.recorder
}

// CreateCohort mocks base method.
func (m *MockCohortStore) CreateCohort(ctx context.Context, params models.CreateCohortParams) (*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCohort", ctx, params)
	ret0, _ := ret[0].(*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCohort indicates an expected call of CreateCohort.
func (mr *MockCohortStoreMockRecorder) CreateCohort(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCohort", reflect.TypeOf((*MockCohortStore)(nil).CreateCohort), ctx, params)
}

// DeleteCohortMemberships mocks base method.
func (m *MockCohortStore) DeleteCohortMemberships(ctx context.Context, orgID, cohortID int64, deviceIdentifiers []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCohortMemberships", ctx, orgID, cohortID, deviceIdentifiers)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCohortMemberships indicates an expected call of DeleteCohortMemberships.
func (mr *MockCohortStoreMockRecorder) DeleteCohortMemberships(ctx, orgID, cohortID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCohortMemberships", reflect.TypeOf((*MockCohortStore)(nil).DeleteCohortMemberships), ctx, orgID, cohortID, deviceIdentifiers)
}

// GetCohort mocks base method.
func (m *MockCohortStore) GetCohort(ctx context.Context, orgID, cohortID int64) (*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCohort", ctx, orgID, cohortID)
	ret0, _ := ret[0].(*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCohort indicates an expected call of GetCohort.
func (mr *MockCohortStoreMockRecorder) GetCohort(ctx, orgID, cohortID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCohort", reflect.TypeOf((*MockCohortStore)(nil).GetCohort), ctx, orgID, cohortID)
}

// InsertCohortMember mocks base method.
func (m *MockCohortStore) InsertCohortMember(ctx context.Context, params models.InsertCohortMemberParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCohortMember", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertCohortMember indicates an expected call of InsertCohortMember.
func (mr *MockCohortStoreMockRecorder) InsertCohortMember(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCohortMember", reflect.TypeOf((*MockCohortStore)(nil).InsertCohortMember), ctx, params)
}

// ListCohortMembers mocks base method.
func (m *MockCohortStore) ListCohortMembers(ctx context.Context, orgID, cohortID int64) ([]models.CohortMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCohortMembers", ctx, orgID, cohortID)
	ret0, _ := ret[0].([]models.CohortMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCohortMembers indicates an expected call of ListCohortMembers.
func (mr *MockCohortStoreMockRecorder) ListCohortMembers(ctx, orgID, cohortID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCohortMembers", reflect.TypeOf((*MockCohortStore)(nil).ListCohortMembers), ctx, orgID, cohortID)
}

// ListCohorts mocks base method.
func (m *MockCohortStore) ListCohorts(ctx context.Context, params models.ListCohortsParams) ([]*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCohorts", ctx, params)
	ret0, _ := ret[0].([]*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCohorts indicates an expected call of ListCohorts.
func (mr *MockCohortStoreMockRecorder) ListCohorts(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCohorts", reflect.TypeOf((*MockCohortStore)(nil).ListCohorts), ctx, params)
}

// ListCohortsByOwner mocks base method.
func (m *MockCohortStore) ListCohortsByOwner(ctx context.Context, params models.ListCohortsByOwnerParams) ([]*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCohortsByOwner", ctx, params)
	ret0, _ := ret[0].([]*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCohortsByOwner indicates an expected call of ListCohortsByOwner.
func (mr *MockCohortStoreMockRecorder) ListCohortsByOwner(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCohortsByOwner", reflect.TypeOf((*MockCohortStore)(nil).ListCohortsByOwner), ctx, params)
}

// ListDefaultCohortDevices mocks base method.
func (m *MockCohortStore) ListDefaultCohortDevices(ctx context.Context, orgID int64) ([]models.DefaultCohortDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDefaultCohortDevices", ctx, orgID)
	ret0, _ := ret[0].([]models.DefaultCohortDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDefaultCohortDevices indicates an expected call of ListDefaultCohortDevices.
func (mr *MockCohortStoreMockRecorder) ListDefaultCohortDevices(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDefaultCohortDevices", reflect.TypeOf((*MockCohortStore)(nil).ListDefaultCohortDevices), ctx, orgID)
}

// ReleaseCohort mocks base method.
func (m *MockCohortStore) ReleaseCohort(ctx context.Context, orgID, cohortID int64) (*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseCohort", ctx, orgID, cohortID)
	ret0, _ := ret[0].(*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseCohort indicates an expected call of ReleaseCohort.
func (mr *MockCohortStoreMockRecorder) ReleaseCohort(ctx, orgID, cohortID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseCohort", reflect.TypeOf((*MockCohortStore)(nil).ReleaseCohort), ctx, orgID, cohortID)
}

// ResolveEffectiveCohortForDevice mocks base method.
func (m *MockCohortStore) ResolveEffectiveCohortForDevice(ctx context.Context, orgID int64, deviceIdentifier string) (*models.Cohort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveEffectiveCohortForDevice", ctx, orgID, deviceIdentifier)
	ret0, _ := ret[0].(*models.Cohort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveEffectiveCohortForDevice indicates an expected call of ResolveEffectiveCohortForDevice.
func (mr *MockCohortStoreMockRecorder) ResolveEffectiveCohortForDevice(ctx, orgID, deviceIdentifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveEffectiveCohortForDevice", reflect.TypeOf((*MockCohortStore)(nil).ResolveEffectiveCohortForDevice), ctx, orgID, deviceIdentifier)
}
