// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	commonv1 "github.com/block/proto-fleet/server/generated/grpc/common/v1"
	minercommandv1 "github.com/block/proto-fleet/server/generated/grpc/minercommand/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedMinercommandCommand() *cli.Command {
	return &cli.Command{
		Name:  "minercommand",
		Usage: "Manage minercommand commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"blink-led",
				"Blink led",
				"/minercommand.v1.MinerCommandService/BlinkLED",
				generatedAuthBearer,
				append([]cli.Flag{
				}, generatedMinerSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minercommandv1.BlinkLEDRequest{}
					selector, err := generatedBuildMinerSelector(ctx, cmd, client)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					return req, nil
				},
				func() proto.Message { return &minercommandv1.BlinkLEDResponse{} },
			),
			generatedRequestCommand(
				"check-capabilities",
				"Check command capabilities",
				"/minercommand.v1.MinerCommandService/CheckCommandCapabilities",
				generatedAuthBearer,
				append([]cli.Flag{
					&cli.StringFlag{Name: "command-type", Usage: "command type. Valid options: reboot, start-mining, stop-mining, blink-led, set-cooling-mode, update-mining-pools, download-logs, firmware-update, set-power-target, update-miner-password, curtail, uncurtail"},
				}, generatedMinerSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minercommandv1.CheckCommandCapabilitiesRequest{}
					selector, err := generatedBuildMinerSelector(ctx, cmd, client)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					if cmd.IsSet("command-type") {
						switch normalizeEnum(cmd.String("command-type")) {
						case "reboot":
							req.CommandType = minercommandv1.CommandType_COMMAND_TYPE_REBOOT
						case "start-mining":
							req.CommandType = minercommandv1.CommandType_COMMAND_TYPE_START_MINING
						case "stop-mining":
							req.CommandType = minercommandv1.CommandType_COMMAND_TYPE_STOP_MINING
						case "blink-led":
							req.CommandType = minercommandv1.CommandType_COMMAND_TYPE_BLINK_LED
						case "set-cooling-mode":
							req.CommandType = minercommandv1.CommandType_COMMAND_TYPE_SET_COOLING_MODE
						case "update-mining-pools":
							req.CommandType = minercommandv1.CommandType_COMMAND_TYPE_UPDATE_MINING_POOLS
						case "download-logs":
							req.CommandType = minercommandv1.CommandType_COMMAND_TYPE_DOWNLOAD_LOGS
						case "firmware-update":
							req.CommandType = minercommandv1.CommandType_COMMAND_TYPE_FIRMWARE_UPDATE
						case "set-power-target":
							req.CommandType = minercommandv1.CommandType_COMMAND_TYPE_SET_POWER_TARGET
						case "update-miner-password":
							req.CommandType = minercommandv1.CommandType_COMMAND_TYPE_UPDATE_MINER_PASSWORD
						case "curtail":
							req.CommandType = minercommandv1.CommandType_COMMAND_TYPE_CURTAIL
						case "uncurtail":
							req.CommandType = minercommandv1.CommandType_COMMAND_TYPE_UNCURTAIL
						default:
							return nil, fmt.Errorf("invalid value for command-type: %s. Valid options: reboot, start-mining, stop-mining, blink-led, set-cooling-mode, update-mining-pools, download-logs, firmware-update, set-power-target, update-miner-password, curtail, uncurtail", cmd.String("command-type"))
						}
					}
					return req, nil
				},
				func() proto.Message { return &minercommandv1.CheckCommandCapabilitiesResponse{} },
			),
			generatedRequestCommand(
				"download-logs",
				"Download logs",
				"/minercommand.v1.MinerCommandService/DownloadLogs",
				generatedAuthBearer,
				append([]cli.Flag{
				}, generatedMinerSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minercommandv1.DownloadLogsRequest{}
					selector, err := generatedBuildMinerSelector(ctx, cmd, client)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					return req, nil
				},
				func() proto.Message { return &minercommandv1.DownloadLogsResponse{} },
			),
			generatedRequestCommand(
				"firmware-update",
				"Firmware update",
				"/minercommand.v1.MinerCommandService/FirmwareUpdate",
				generatedAuthBearer,
				append([]cli.Flag{
					&cli.StringFlag{Name: "firmware-file-id", Usage: "firmware file id"},
				}, generatedMinerSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minercommandv1.FirmwareUpdateRequest{}
					selector, err := generatedBuildMinerSelector(ctx, cmd, client)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					if cmd.IsSet("firmware-file-id") {
						req.FirmwareFileId = cmd.String("firmware-file-id")
					}
					return req, nil
				},
				func() proto.Message { return &minercommandv1.FirmwareUpdateResponse{} },
			),
			generatedRequestCommand(
				"get-command-batch-device-results",
				"Get command batch device results",
				"/minercommand.v1.MinerCommandService/GetCommandBatchDeviceResults",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "batch-identifier", Usage: "batch identifier"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minercommandv1.GetCommandBatchDeviceResultsRequest{}
					if cmd.IsSet("batch-identifier") {
						req.BatchIdentifier = cmd.String("batch-identifier")
					}
					return req, nil
				},
				func() proto.Message { return &minercommandv1.GetCommandBatchDeviceResultsResponse{} },
			),
			generatedRequestCommand(
				"reboot",
				"Reboot",
				"/minercommand.v1.MinerCommandService/Reboot",
				generatedAuthBearer,
				append([]cli.Flag{
				}, generatedMinerSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minercommandv1.RebootRequest{}
					selector, err := generatedBuildMinerSelector(ctx, cmd, client)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					return req, nil
				},
				func() proto.Message { return &minercommandv1.RebootResponse{} },
			),
			generatedRequestCommand(
				"set-cooling-mode",
				"Set cooling mode",
				"/minercommand.v1.MinerCommandService/SetCoolingMode",
				generatedAuthBearer,
				append([]cli.Flag{
					&cli.StringFlag{Name: "mode", Usage: "mode. Valid options: air-cooled, immersion-cooled, manual"},
				}, generatedMinerSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minercommandv1.SetCoolingModeRequest{}
					selector, err := generatedBuildMinerSelector(ctx, cmd, client)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					if cmd.IsSet("mode") {
						switch normalizeEnum(cmd.String("mode")) {
						case "air-cooled":
							req.Mode = commonv1.CoolingMode_COOLING_MODE_AIR_COOLED
						case "immersion-cooled":
							req.Mode = commonv1.CoolingMode_COOLING_MODE_IMMERSION_COOLED
						case "manual":
							req.Mode = commonv1.CoolingMode_COOLING_MODE_MANUAL
						default:
							return nil, fmt.Errorf("invalid value for mode: %s. Valid options: air-cooled, immersion-cooled, manual", cmd.String("mode"))
						}
					}
					return req, nil
				},
				func() proto.Message { return &minercommandv1.SetCoolingModeResponse{} },
			),
			generatedRequestCommand(
				"set-power-target",
				"Set power target",
				"/minercommand.v1.MinerCommandService/SetPowerTarget",
				generatedAuthBearer,
				append([]cli.Flag{
					&cli.StringFlag{Name: "performance-mode", Usage: "performance mode. Valid options: maximum-hashrate, efficiency"},
				}, generatedMinerSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minercommandv1.SetPowerTargetRequest{}
					selector, err := generatedBuildMinerSelector(ctx, cmd, client)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					if cmd.IsSet("performance-mode") {
						switch normalizeEnum(cmd.String("performance-mode")) {
						case "maximum-hashrate":
							req.PerformanceMode = minercommandv1.PerformanceMode_PERFORMANCE_MODE_MAXIMUM_HASHRATE
						case "efficiency":
							req.PerformanceMode = minercommandv1.PerformanceMode_PERFORMANCE_MODE_EFFICIENCY
						default:
							return nil, fmt.Errorf("invalid value for performance-mode: %s. Valid options: maximum-hashrate, efficiency", cmd.String("performance-mode"))
						}
					}
					return req, nil
				},
				func() proto.Message { return &minercommandv1.SetPowerTargetResponse{} },
			),
			generatedRequestCommand(
				"start",
				"Start mining",
				"/minercommand.v1.MinerCommandService/StartMining",
				generatedAuthBearer,
				append([]cli.Flag{
				}, generatedMinerSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minercommandv1.StartMiningRequest{}
					selector, err := generatedBuildMinerSelector(ctx, cmd, client)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					return req, nil
				},
				func() proto.Message { return &minercommandv1.StartMiningResponse{} },
			),
			generatedRequestCommand(
				"stop",
				"Stop mining",
				"/minercommand.v1.MinerCommandService/StopMining",
				generatedAuthBearer,
				append([]cli.Flag{
				}, generatedMinerSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minercommandv1.StopMiningRequest{}
					selector, err := generatedBuildMinerSelector(ctx, cmd, client)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					return req, nil
				},
				func() proto.Message { return &minercommandv1.StopMiningResponse{} },
			),
			generatedRequestCommand(
				"unpair",
				"Unpair",
				"/minercommand.v1.MinerCommandService/Unpair",
				generatedAuthBearer,
				append([]cli.Flag{
				}, generatedMinerSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minercommandv1.UnpairRequest{}
					selector, err := generatedBuildMinerSelector(ctx, cmd, client)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					return req, nil
				},
				func() proto.Message { return &minercommandv1.UnpairResponse{} },
			),
			generatedRequestCommand(
				"update-password",
				"Update miner password",
				"/minercommand.v1.MinerCommandService/UpdateMinerPassword",
				generatedAuthBearer,
				append([]cli.Flag{
					&cli.StringFlag{Name: "new-password", Usage: "new password"},
					&cli.StringFlag{Name: "current-password", Usage: "current password"},
					&cli.StringFlag{Name: "user-username", Usage: "user username"},
					&cli.StringFlag{Name: "user-password", Usage: "user password"},
				}, generatedMinerSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minercommandv1.UpdateMinerPasswordRequest{}
					selector, err := generatedBuildMinerSelector(ctx, cmd, client)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					if cmd.IsSet("new-password") {
						req.NewPassword = cmd.String("new-password")
					}
					if cmd.IsSet("current-password") {
						req.CurrentPassword = cmd.String("current-password")
					}
					if cmd.IsSet("user-username") {
						req.UserUsername = cmd.String("user-username")
					}
					if cmd.IsSet("user-password") {
						req.UserPassword = cmd.String("user-password")
					}
					return req, nil
				},
				func() proto.Message { return &minercommandv1.UpdateMinerPasswordResponse{} },
			),
			generatedRequestCommand(
				"update-pools",
				"Update mining pools",
				"/minercommand.v1.MinerCommandService/UpdateMiningPools",
				generatedAuthBearer,
				append([]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.StringFlag{Name: "user-username", Usage: "user username"},
					&cli.StringFlag{Name: "user-password", Usage: "user password"},
				}, generatedMinerSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minercommandv1.UpdateMiningPoolsRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if cmd.IsSet("all-devices") || cmd.IsSet("device") || cmd.IsSet("group-id") || cmd.IsSet("group") || cmd.IsSet("rack-id") || cmd.IsSet("rack") {
						selector, err := generatedBuildMinerSelector(ctx, cmd, client)
						if err != nil {
							return nil, err
						}
						req.DeviceSelector = selector
					}
					if cmd.IsSet("user-username") {
						req.UserUsername = cmd.String("user-username")
					}
					if cmd.IsSet("user-password") {
						req.UserPassword = cmd.String("user-password")
					}
					return req, nil
				},
				func() proto.Message { return &minercommandv1.UpdateMiningPoolsResponse{} },
			),
		},
	}
}
