// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	fleetmanagementv1 "github.com/block/proto-fleet/server/generated/grpc/fleetmanagement/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedMinersCommand() *cli.Command {
	return &cli.Command{
		Name:  "miners",
		Usage: "Manage miners commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"list",
				"List miner state snapshots",
				"/fleetmanagement.v1.FleetManagementService/ListMinerStateSnapshots",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "cursor", Usage: "cursor"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &fleetmanagementv1.ListMinerStateSnapshotsRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("cursor") {
						req.Cursor = cmd.String("cursor")
					}
					return req, nil
				},
				func() proto.Message { return &fleetmanagementv1.ListMinerStateSnapshotsResponse{} },
			),
		},
	}
}
