// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	schedulev1 "github.com/block/proto-fleet/server/generated/grpc/schedule/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedScheduleCommand() *cli.Command {
	return &cli.Command{
		Name:  "schedule",
		Usage: "Manage schedule commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"create",
				"Create schedule",
				"/schedule.v1.ScheduleService/CreateSchedule",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.StringFlag{Name: "name", Usage: "name"},
					&cli.StringFlag{Name: "action", Usage: "action. Valid options: set-power-target, reboot, sleep"},
					&cli.StringFlag{Name: "schedule-type", Usage: "schedule type. Valid options: one-time, recurring"},
					&cli.StringFlag{Name: "start-date", Usage: "start date"},
					&cli.StringFlag{Name: "start-time", Usage: "start time"},
					&cli.StringFlag{Name: "end-time", Usage: "end time"},
					&cli.StringFlag{Name: "end-date", Usage: "end date"},
					&cli.StringFlag{Name: "timezone", Usage: "timezone"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &schedulev1.CreateScheduleRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if cmd.IsSet("name") {
						req.Name = cmd.String("name")
					}
					if cmd.IsSet("action") {
						switch normalizeEnum(cmd.String("action")) {
						case "set-power-target":
							req.Action = schedulev1.ScheduleAction_SCHEDULE_ACTION_SET_POWER_TARGET
						case "reboot":
							req.Action = schedulev1.ScheduleAction_SCHEDULE_ACTION_REBOOT
						case "sleep":
							req.Action = schedulev1.ScheduleAction_SCHEDULE_ACTION_SLEEP
						default:
							return nil, fmt.Errorf("invalid value for action: %s. Valid options: set-power-target, reboot, sleep", cmd.String("action"))
						}
					}
					if cmd.IsSet("schedule-type") {
						switch normalizeEnum(cmd.String("schedule-type")) {
						case "one-time":
							req.ScheduleType = schedulev1.ScheduleType_SCHEDULE_TYPE_ONE_TIME
						case "recurring":
							req.ScheduleType = schedulev1.ScheduleType_SCHEDULE_TYPE_RECURRING
						default:
							return nil, fmt.Errorf("invalid value for schedule-type: %s. Valid options: one-time, recurring", cmd.String("schedule-type"))
						}
					}
					if cmd.IsSet("start-date") {
						req.StartDate = cmd.String("start-date")
					}
					if cmd.IsSet("start-time") {
						req.StartTime = cmd.String("start-time")
					}
					if cmd.IsSet("end-time") {
						req.EndTime = cmd.String("end-time")
					}
					if cmd.IsSet("end-date") {
						req.EndDate = cmd.String("end-date")
					}
					if cmd.IsSet("timezone") {
						req.Timezone = cmd.String("timezone")
					}
					return req, nil
				},
				func() proto.Message { return &schedulev1.CreateScheduleResponse{} },
			),
			generatedRequestCommand(
				"delete",
				"Delete schedule",
				"/schedule.v1.ScheduleService/DeleteSchedule",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "schedule-id", Usage: "schedule id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &schedulev1.DeleteScheduleRequest{}
					if cmd.IsSet("schedule-id") {
						req.ScheduleId = cmd.Int64("schedule-id")
					}
					return req, nil
				},
				func() proto.Message { return &schedulev1.DeleteScheduleResponse{} },
			),
			generatedRequestCommand(
				"list",
				"List schedules",
				"/schedule.v1.ScheduleService/ListSchedules",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "status", Usage: "status. Valid options: active, paused, running, completed"},
					&cli.StringFlag{Name: "action", Usage: "action. Valid options: set-power-target, reboot, sleep"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &schedulev1.ListSchedulesRequest{}
					if cmd.IsSet("status") {
						switch normalizeEnum(cmd.String("status")) {
						case "active":
							req.Status = schedulev1.ScheduleStatus_SCHEDULE_STATUS_ACTIVE
						case "paused":
							req.Status = schedulev1.ScheduleStatus_SCHEDULE_STATUS_PAUSED
						case "running":
							req.Status = schedulev1.ScheduleStatus_SCHEDULE_STATUS_RUNNING
						case "completed":
							req.Status = schedulev1.ScheduleStatus_SCHEDULE_STATUS_COMPLETED
						default:
							return nil, fmt.Errorf("invalid value for status: %s. Valid options: active, paused, running, completed", cmd.String("status"))
						}
					}
					if cmd.IsSet("action") {
						switch normalizeEnum(cmd.String("action")) {
						case "set-power-target":
							req.Action = schedulev1.ScheduleAction_SCHEDULE_ACTION_SET_POWER_TARGET
						case "reboot":
							req.Action = schedulev1.ScheduleAction_SCHEDULE_ACTION_REBOOT
						case "sleep":
							req.Action = schedulev1.ScheduleAction_SCHEDULE_ACTION_SLEEP
						default:
							return nil, fmt.Errorf("invalid value for action: %s. Valid options: set-power-target, reboot, sleep", cmd.String("action"))
						}
					}
					return req, nil
				},
				func() proto.Message { return &schedulev1.ListSchedulesResponse{} },
			),
			generatedRequestCommand(
				"pause",
				"Pause schedule",
				"/schedule.v1.ScheduleService/PauseSchedule",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "schedule-id", Usage: "schedule id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &schedulev1.PauseScheduleRequest{}
					if cmd.IsSet("schedule-id") {
						req.ScheduleId = cmd.Int64("schedule-id")
					}
					return req, nil
				},
				func() proto.Message { return &schedulev1.PauseScheduleResponse{} },
			),
			generatedRequestCommand(
				"reorder",
				"Reorder schedules",
				"/schedule.v1.ScheduleService/ReorderSchedules",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringSliceFlag{Name: "schedule-ids", Usage: "schedule ids"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &schedulev1.ReorderSchedulesRequest{}
					if cmd.IsSet("schedule-ids") {
						values, err := parseInt64Slice(cmd.StringSlice("schedule-ids"))
						if err != nil {
							return nil, err
						}
						req.ScheduleIds = values
					}
					return req, nil
				},
				func() proto.Message { return &schedulev1.ReorderSchedulesResponse{} },
			),
			generatedRequestCommand(
				"resume",
				"Resume schedule",
				"/schedule.v1.ScheduleService/ResumeSchedule",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "schedule-id", Usage: "schedule id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &schedulev1.ResumeScheduleRequest{}
					if cmd.IsSet("schedule-id") {
						req.ScheduleId = cmd.Int64("schedule-id")
					}
					return req, nil
				},
				func() proto.Message { return &schedulev1.ResumeScheduleResponse{} },
			),
			generatedRequestCommand(
				"update",
				"Update schedule",
				"/schedule.v1.ScheduleService/UpdateSchedule",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.Int64Flag{Name: "schedule-id", Usage: "schedule id"},
					&cli.StringFlag{Name: "name", Usage: "name"},
					&cli.StringFlag{Name: "action", Usage: "action. Valid options: set-power-target, reboot, sleep"},
					&cli.StringFlag{Name: "schedule-type", Usage: "schedule type. Valid options: one-time, recurring"},
					&cli.StringFlag{Name: "start-date", Usage: "start date"},
					&cli.StringFlag{Name: "start-time", Usage: "start time"},
					&cli.StringFlag{Name: "end-time", Usage: "end time"},
					&cli.StringFlag{Name: "end-date", Usage: "end date"},
					&cli.StringFlag{Name: "timezone", Usage: "timezone"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &schedulev1.UpdateScheduleRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if cmd.IsSet("schedule-id") {
						req.ScheduleId = cmd.Int64("schedule-id")
					}
					if cmd.IsSet("name") {
						req.Name = cmd.String("name")
					}
					if cmd.IsSet("action") {
						switch normalizeEnum(cmd.String("action")) {
						case "set-power-target":
							req.Action = schedulev1.ScheduleAction_SCHEDULE_ACTION_SET_POWER_TARGET
						case "reboot":
							req.Action = schedulev1.ScheduleAction_SCHEDULE_ACTION_REBOOT
						case "sleep":
							req.Action = schedulev1.ScheduleAction_SCHEDULE_ACTION_SLEEP
						default:
							return nil, fmt.Errorf("invalid value for action: %s. Valid options: set-power-target, reboot, sleep", cmd.String("action"))
						}
					}
					if cmd.IsSet("schedule-type") {
						switch normalizeEnum(cmd.String("schedule-type")) {
						case "one-time":
							req.ScheduleType = schedulev1.ScheduleType_SCHEDULE_TYPE_ONE_TIME
						case "recurring":
							req.ScheduleType = schedulev1.ScheduleType_SCHEDULE_TYPE_RECURRING
						default:
							return nil, fmt.Errorf("invalid value for schedule-type: %s. Valid options: one-time, recurring", cmd.String("schedule-type"))
						}
					}
					if cmd.IsSet("start-date") {
						req.StartDate = cmd.String("start-date")
					}
					if cmd.IsSet("start-time") {
						req.StartTime = cmd.String("start-time")
					}
					if cmd.IsSet("end-time") {
						req.EndTime = cmd.String("end-time")
					}
					if cmd.IsSet("end-date") {
						req.EndDate = cmd.String("end-date")
					}
					if cmd.IsSet("timezone") {
						req.Timezone = cmd.String("timezone")
					}
					return req, nil
				},
				func() proto.Message { return &schedulev1.UpdateScheduleResponse{} },
			),
		},
	}
}
