// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	networkinfov1 "github.com/block/proto-fleet/server/generated/grpc/networkinfo/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedNetworkinfoCommand() *cli.Command {
	return &cli.Command{
		Name:  "networkinfo",
		Usage: "Manage networkinfo commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"get",
				"Get network info",
				"/networkinfo.v1.NetworkInfoService/GetNetworkInfo",
				generatedAuthBearer,
				[]cli.Flag{
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &networkinfov1.GetNetworkInfoRequest{}
					return req, nil
				},
				func() proto.Message { return &networkinfov1.GetNetworkInfoResponse{} },
			),
			generatedRequestCommand(
				"set-nickname",
				"Update network nickname",
				"/networkinfo.v1.NetworkInfoService/UpdateNetworkNickname",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "network-nickname", Usage: "network nickname"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &networkinfov1.UpdateNetworkNicknameRequest{}
					if cmd.IsSet("network-nickname") {
						req.NetworkNickname = cmd.String("network-nickname")
					}
					return req, nil
				},
				func() proto.Message { return &networkinfov1.UpdateNetworkNicknameResponse{} },
			),
		},
	}
}
