// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	collectionv1 "github.com/block/proto-fleet/server/generated/grpc/collection/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedGroupsCommand() *cli.Command {
	return &cli.Command{
		Name:  "groups",
		Usage: "Manage groups commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"add-devices",
				"Add devices to a group",
				"/collection.v1.DeviceCollectionService/AddDevicesToCollection",
				generatedAuthBearer,
				append([]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
				}, generatedCommonSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.AddDevicesToCollectionRequest{}
					selector, err := generatedBuildCommonSelector(cmd)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.AddDevicesToCollectionResponse{} },
			),
			generatedRequestCommand(
				"create",
				"Create a group",
				"/collection.v1.DeviceCollectionService/CreateCollection",
				generatedAuthBearer,
				append([]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.StringFlag{Name: "label", Usage: "label"},
					&cli.StringFlag{Name: "description", Usage: "description"},
				}, generatedCommonSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.CreateCollectionRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if generatedCommonSelectorProvided(cmd) {
						selector, err := generatedBuildCommonSelector(cmd)
						if err != nil {
							return nil, err
						}
						req.DeviceSelector = selector
					}
					req.Type = collectionv1.CollectionType_COLLECTION_TYPE_GROUP
					if cmd.IsSet("label") {
						req.Label = cmd.String("label")
					}
					if cmd.IsSet("description") {
						req.Description = cmd.String("description")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.CreateCollectionResponse{} },
			),
			generatedRequestCommand(
				"delete",
				"Delete a group",
				"/collection.v1.DeviceCollectionService/DeleteCollection",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.DeleteCollectionRequest{}
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.DeleteCollectionResponse{} },
			),
			generatedRequestCommand(
				"device",
				"List groups for a device identifier",
				"/collection.v1.DeviceCollectionService/GetDeviceCollections",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "device-identifier", Usage: "device identifier"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.GetDeviceCollectionsRequest{}
					req.Type = collectionv1.CollectionType_COLLECTION_TYPE_GROUP
					if cmd.IsSet("device-identifier") {
						req.DeviceIdentifier = cmd.String("device-identifier")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.GetDeviceCollectionsResponse{} },
			),
			generatedRequestCommand(
				"get",
				"Get a group by id",
				"/collection.v1.DeviceCollectionService/GetCollection",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.GetCollectionRequest{}
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.GetCollectionResponse{} },
			),
			generatedRequestCommand(
				"list",
				"List groups",
				"/collection.v1.DeviceCollectionService/ListCollections",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.ListCollectionsRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					req.Type = collectionv1.CollectionType_COLLECTION_TYPE_GROUP
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.ListCollectionsResponse{} },
			),
			generatedRequestCommand(
				"members",
				"List group members",
				"/collection.v1.DeviceCollectionService/ListCollectionMembers",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.ListCollectionMembersRequest{}
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.ListCollectionMembersResponse{} },
			),
			generatedRequestCommand(
				"remove-devices",
				"Remove devices from a group",
				"/collection.v1.DeviceCollectionService/RemoveDevicesFromCollection",
				generatedAuthBearer,
				append([]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
				}, generatedCommonSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.RemoveDevicesFromCollectionRequest{}
					selector, err := generatedBuildCommonSelector(cmd)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.RemoveDevicesFromCollectionResponse{} },
			),
			generatedRequestCommand(
				"stats",
				"Get aggregated stats for one or more groups",
				"/collection.v1.DeviceCollectionService/GetCollectionStats",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringSliceFlag{Name: "collection-ids", Usage: "collection ids"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.GetCollectionStatsRequest{}
					if cmd.IsSet("collection-ids") {
						values, err := parseInt64Slice(cmd.StringSlice("collection-ids"))
						if err != nil {
							return nil, err
						}
						req.CollectionIds = values
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.GetCollectionStatsResponse{} },
			),
			generatedRequestCommand(
				"update",
				"Update a group",
				"/collection.v1.DeviceCollectionService/UpdateCollection",
				generatedAuthBearer,
				append([]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
					&cli.StringFlag{Name: "label", Usage: "label"},
					&cli.StringFlag{Name: "description", Usage: "description"},
				}, generatedCommonSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.UpdateCollectionRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if generatedCommonSelectorProvided(cmd) {
						selector, err := generatedBuildCommonSelector(cmd)
						if err != nil {
							return nil, err
						}
						req.DeviceSelector = selector
					}
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					if cmd.IsSet("label") {
						value := cmd.String("label")
						req.Label = &value
					}
					if cmd.IsSet("description") {
						value := cmd.String("description")
						req.Description = &value
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.UpdateCollectionResponse{} },
			),
		},
	}
}
