// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	onboardingv1 "github.com/block/proto-fleet/server/generated/grpc/onboarding/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedOnboardingCommand() *cli.Command {
	return &cli.Command{
		Name:  "onboarding",
		Usage: "Manage onboarding commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"create-admin",
				"Create the initial Fleet admin login",
				"/onboarding.v1.OnboardingService/CreateAdminLogin",
				generatedAuthAnonymous,
				[]cli.Flag{
					&cli.StringFlag{Name: "username", Usage: "username"},
					&cli.StringFlag{Name: "password", Usage: "password"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &onboardingv1.CreateAdminLoginRequest{}
					if cmd.IsSet("username") {
						req.Username = cmd.String("username")
					}
					if cmd.IsSet("password") {
						req.Password = cmd.String("password")
					}
					return req, nil
				},
				func() proto.Message { return &onboardingv1.CreateAdminLoginResponse{} },
			),
		},
	}
}
