// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	cohortv1 "github.com/block/proto-fleet/server/generated/grpc/cohort/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedCohortsCommand() *cli.Command {
	return &cli.Command{
		Name:  "cohorts",
		Usage: "Manage cohorts commands",
		Commands: append(manualGroupCommands("cohorts"), []*cli.Command{
			generatedRequestCommand(
				"add-devices",
				"Add devices to cohort",
				"/cohort.v1.CohortService/AddDevicesToCohort",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "cohort-id", Usage: "cohort id"},
					&cli.StringSliceFlag{Name: "device-identifiers", Usage: "device identifiers"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &cohortv1.AddDevicesToCohortRequest{}
					if cmd.IsSet("cohort-id") {
						req.CohortId = cmd.Int64("cohort-id")
					}
					if cmd.IsSet("device-identifiers") {
						req.DeviceIdentifiers = cmd.StringSlice("device-identifiers")
					}
					return req, nil
				},
				func() proto.Message { return &cohortv1.AddDevicesToCohortResponse{} },
			),
			generatedRequestCommand(
				"admin-reassign",
				"Admin reassign",
				"/cohort.v1.CohortService/AdminReassign",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "target-cohort-id", Usage: "target cohort id"},
					&cli.StringSliceFlag{Name: "device-identifiers", Usage: "device identifiers"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &cohortv1.AdminReassignRequest{}
					if cmd.IsSet("target-cohort-id") {
						req.TargetCohortId = cmd.Int64("target-cohort-id")
					}
					if cmd.IsSet("device-identifiers") {
						req.DeviceIdentifiers = cmd.StringSlice("device-identifiers")
					}
					return req, nil
				},
				func() proto.Message { return &cohortv1.AdminReassignResponse{} },
			),
			generatedRequestCommand(
				"admin-release",
				"Admin release cohort",
				"/cohort.v1.CohortService/AdminReleaseCohort",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "cohort-id", Usage: "cohort id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &cohortv1.AdminReleaseCohortRequest{}
					if cmd.IsSet("cohort-id") {
						req.CohortId = cmd.Int64("cohort-id")
					}
					return req, nil
				},
				func() proto.Message { return &cohortv1.AdminReleaseCohortResponse{} },
			),
			generatedRequestCommand(
				"create",
				"Create cohort",
				"/cohort.v1.CohortService/CreateCohort",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.StringFlag{Name: "label", Usage: "label"},
					&cli.StringFlag{Name: "purpose", Usage: "purpose"},
					&cli.BoolFlag{Name: "claim-ownership", Usage: "claim ownership"},
					&cli.StringFlag{Name: "expires-at", Usage: "expires at"},
					&cli.StringFlag{Name: "desired-firmware-file-id", Usage: "desired firmware file id"},
					&cli.Int64Flag{Name: "source-device-set-id", Usage: "source device set id"},
					&cli.StringFlag{Name: "idempotency-key", Usage: "idempotency key"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &cohortv1.CreateCohortRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if cmd.IsSet("label") {
						req.Label = cmd.String("label")
					}
					if cmd.IsSet("purpose") {
						req.Purpose = cmd.String("purpose")
					}
					if cmd.IsSet("claim-ownership") {
						req.ClaimOwnership = cmd.Bool("claim-ownership")
					}
					if cmd.IsSet("expires-at") {
						parsed, err := parseRFC3339Timestamp(cmd.String("expires-at"), "expires-at")
						if err != nil {
							return nil, err
						}
						req.ExpiresAt = parsed
					}
					if cmd.IsSet("desired-firmware-file-id") {
						req.DesiredFirmwareFileId = cmd.String("desired-firmware-file-id")
					}
					if cmd.IsSet("source-device-set-id") {
						req.InitialMembers = &cohortv1.CreateCohortRequest_SourceDeviceSetId{SourceDeviceSetId: cmd.Int64("source-device-set-id")}
					}
					if cmd.IsSet("idempotency-key") {
						req.IdempotencyKey = cmd.String("idempotency-key")
					}
					return req, nil
				},
				func() proto.Message { return &cohortv1.CreateCohortResponse{} },
			),
			generatedRequestCommand(
				"delete",
				"Delete cohort",
				"/cohort.v1.CohortService/DeleteCohort",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "cohort-id", Usage: "cohort id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &cohortv1.DeleteCohortRequest{}
					if cmd.IsSet("cohort-id") {
						req.CohortId = cmd.Int64("cohort-id")
					}
					return req, nil
				},
				func() proto.Message { return &cohortv1.DeleteCohortResponse{} },
			),
			generatedRequestCommand(
				"extend",
				"Update cohort",
				"/cohort.v1.CohortService/UpdateCohort",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.Int64Flag{Name: "cohort-id", Usage: "cohort id"},
					&cli.StringFlag{Name: "label", Usage: "label"},
					&cli.StringFlag{Name: "purpose", Usage: "purpose"},
					&cli.StringFlag{Name: "expires-at", Usage: "expires at"},
					&cli.StringFlag{Name: "desired-firmware-file-id", Usage: "desired firmware file id"},
					&cli.BoolFlag{Name: "clear-expires-at", Usage: "clear expires at"},
					&cli.BoolFlag{Name: "clear-desired-config", Usage: "clear desired config"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &cohortv1.UpdateCohortRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if cmd.IsSet("cohort-id") {
						req.CohortId = cmd.Int64("cohort-id")
					}
					if cmd.IsSet("label") {
						value := cmd.String("label")
						req.Label = &value
					}
					if cmd.IsSet("purpose") {
						value := cmd.String("purpose")
						req.Purpose = &value
					}
					if cmd.IsSet("expires-at") {
						parsed, err := parseRFC3339Timestamp(cmd.String("expires-at"), "expires-at")
						if err != nil {
							return nil, err
						}
						req.ExpiresAt = parsed
					}
					if cmd.IsSet("desired-firmware-file-id") {
						value := cmd.String("desired-firmware-file-id")
						req.DesiredFirmwareFileId = &value
					}
					if cmd.IsSet("clear-expires-at") {
						req.ClearExpiresAt = cmd.Bool("clear-expires-at")
					}
					if cmd.IsSet("clear-desired-config") {
						req.ClearDesiredConfig = cmd.Bool("clear-desired-config")
					}
					return req, nil
				},
				func() proto.Message { return &cohortv1.UpdateCohortResponse{} },
			),
			generatedRequestCommand(
				"list",
				"List cohorts",
				"/cohort.v1.CohortService/ListCohorts",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.BoolFlag{Name: "include-released", Usage: "include released"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
					&cli.StringFlag{Name: "search", Usage: "search"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &cohortv1.ListCohortsRequest{}
					if cmd.IsSet("include-released") {
						req.IncludeReleased = cmd.Bool("include-released")
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					if cmd.IsSet("search") {
						req.Search = cmd.String("search")
					}
					return req, nil
				},
				func() proto.Message { return &cohortv1.ListCohortsResponse{} },
			),
			generatedRequestCommand(
				"my",
				"Get my cohorts",
				"/cohort.v1.CohortService/GetMyCohorts",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.BoolFlag{Name: "include-released", Usage: "include released"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
					&cli.StringFlag{Name: "search", Usage: "search"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &cohortv1.GetMyCohortsRequest{}
					if cmd.IsSet("include-released") {
						req.IncludeReleased = cmd.Bool("include-released")
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					if cmd.IsSet("search") {
						req.Search = cmd.String("search")
					}
					return req, nil
				},
				func() proto.Message { return &cohortv1.GetMyCohortsResponse{} },
			),
			generatedRequestCommand(
				"release",
				"Release cohort",
				"/cohort.v1.CohortService/ReleaseCohort",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "cohort-id", Usage: "cohort id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &cohortv1.ReleaseCohortRequest{}
					if cmd.IsSet("cohort-id") {
						req.CohortId = cmd.Int64("cohort-id")
					}
					return req, nil
				},
				func() proto.Message { return &cohortv1.ReleaseCohortResponse{} },
			),
			generatedRequestCommand(
				"remove-devices",
				"Remove devices from cohort",
				"/cohort.v1.CohortService/RemoveDevicesFromCohort",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "cohort-id", Usage: "cohort id"},
					&cli.StringSliceFlag{Name: "device-identifiers", Usage: "device identifiers"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &cohortv1.RemoveDevicesFromCohortRequest{}
					if cmd.IsSet("cohort-id") {
						req.CohortId = cmd.Int64("cohort-id")
					}
					if cmd.IsSet("device-identifiers") {
						req.DeviceIdentifiers = cmd.StringSlice("device-identifiers")
					}
					return req, nil
				},
				func() proto.Message { return &cohortv1.RemoveDevicesFromCohortResponse{} },
			),
			generatedRequestCommand(
				"rigs",
				"List devices",
				"/cohort.v1.CohortService/ListDevices",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.Int64Flag{Name: "site-id", Usage: "site id"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &cohortv1.ListDevicesRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if cmd.IsSet("site-id") {
						value := cmd.Int64("site-id")
						req.SiteId = &value
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					return req, nil
				},
				func() proto.Message { return &cohortv1.ListDevicesResponse{} },
			),
			generatedRequestCommand(
				"set-cohort-firmware-target",
				"Set cohort firmware target",
				"/cohort.v1.CohortService/SetCohortFirmwareTarget",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "cohort-id", Usage: "cohort id"},
					&cli.StringFlag{Name: "manufacturer", Usage: "manufacturer"},
					&cli.StringFlag{Name: "model", Usage: "model"},
					&cli.StringFlag{Name: "firmware-file-id", Usage: "firmware file id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &cohortv1.SetCohortFirmwareTargetRequest{}
					if cmd.IsSet("cohort-id") {
						req.CohortId = cmd.Int64("cohort-id")
					}
					if cmd.IsSet("manufacturer") {
						req.Manufacturer = cmd.String("manufacturer")
					}
					if cmd.IsSet("model") {
						req.Model = cmd.String("model")
					}
					if cmd.IsSet("firmware-file-id") {
						value := cmd.String("firmware-file-id")
						req.FirmwareFileId = &value
					}
					return req, nil
				},
				func() proto.Message { return &cohortv1.SetCohortFirmwareTargetResponse{} },
			),
			generatedRequestCommand(
				"status",
				"Get cohort",
				"/cohort.v1.CohortService/GetCohort",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "cohort-id", Usage: "cohort id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &cohortv1.GetCohortRequest{}
					if cmd.IsSet("cohort-id") {
						req.CohortId = cmd.Int64("cohort-id")
					}
					return req, nil
				},
				func() proto.Message { return &cohortv1.GetCohortResponse{} },
			),
		}...),
	}
}
