// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	collectionv1 "github.com/block/proto-fleet/server/generated/grpc/collection/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedRacksCommand() *cli.Command {
	return &cli.Command{
		Name:  "racks",
		Usage: "Manage racks commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"add-devices",
				"Add devices to a rack",
				"/collection.v1.DeviceCollectionService/AddDevicesToCollection",
				generatedAuthBearer,
				append([]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
				}, generatedCommonSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.AddDevicesToCollectionRequest{}
					selector, err := generatedBuildCommonSelector(cmd)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.AddDevicesToCollectionResponse{} },
			),
			generatedRequestCommand(
				"delete",
				"Delete a rack",
				"/collection.v1.DeviceCollectionService/DeleteCollection",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.DeleteCollectionRequest{}
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.DeleteCollectionResponse{} },
			),
			generatedRequestCommand(
				"device",
				"List racks for a device identifier",
				"/collection.v1.DeviceCollectionService/GetDeviceCollections",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "device-identifier", Usage: "device identifier"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.GetDeviceCollectionsRequest{}
					req.Type = collectionv1.CollectionType_COLLECTION_TYPE_RACK
					if cmd.IsSet("device-identifier") {
						req.DeviceIdentifier = cmd.String("device-identifier")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.GetDeviceCollectionsResponse{} },
			),
			generatedRequestCommand(
				"get",
				"Get a rack by id",
				"/collection.v1.DeviceCollectionService/GetCollection",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.GetCollectionRequest{}
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.GetCollectionResponse{} },
			),
			generatedRequestCommand(
				"list",
				"List racks",
				"/collection.v1.DeviceCollectionService/ListCollections",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
					&cli.StringSliceFlag{Name: "zones", Usage: "zones"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.ListCollectionsRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					req.Type = collectionv1.CollectionType_COLLECTION_TYPE_RACK
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					if cmd.IsSet("zones") {
						req.Zones = cmd.StringSlice("zones")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.ListCollectionsResponse{} },
			),
			generatedRequestCommand(
				"members",
				"List rack members",
				"/collection.v1.DeviceCollectionService/ListCollectionMembers",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.ListCollectionMembersRequest{}
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.ListCollectionMembersResponse{} },
			),
			generatedRequestCommand(
				"remove-devices",
				"Remove devices from a rack",
				"/collection.v1.DeviceCollectionService/RemoveDevicesFromCollection",
				generatedAuthBearer,
				append([]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
				}, generatedCommonSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.RemoveDevicesFromCollectionRequest{}
					selector, err := generatedBuildCommonSelector(cmd)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.RemoveDevicesFromCollectionResponse{} },
			),
			generatedRequestCommand(
				"save",
				"Create or update a rack",
				"/collection.v1.DeviceCollectionService/SaveRack",
				generatedAuthBearer,
				append([]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
					&cli.StringFlag{Name: "label", Usage: "label"},
				}, generatedCommonSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.SaveRackRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if cmd.IsSet("all-devices") || cmd.IsSet("device") {
						selector, err := generatedBuildCommonSelector(cmd)
						if err != nil {
							return nil, err
						}
						req.DeviceSelector = selector
					}
					if cmd.IsSet("collection-id") {
						value := cmd.Int64("collection-id")
						req.CollectionId = &value
					}
					if cmd.IsSet("label") {
						req.Label = cmd.String("label")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.SaveRackResponse{} },
			),
			generatedRequestCommand(
				"slots",
				"List occupied rack slots",
				"/collection.v1.DeviceCollectionService/GetRackSlots",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.GetRackSlotsRequest{}
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.GetRackSlotsResponse{} },
			),
			generatedRequestCommand(
				"stats",
				"Get aggregated stats for one or more racks",
				"/collection.v1.DeviceCollectionService/GetCollectionStats",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringSliceFlag{Name: "collection-ids", Usage: "collection ids"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.GetCollectionStatsRequest{}
					if cmd.IsSet("collection-ids") {
						values, err := parseInt64Slice(cmd.StringSlice("collection-ids"))
						if err != nil {
							return nil, err
						}
						req.CollectionIds = values
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.GetCollectionStatsResponse{} },
			),
			generatedRequestCommand(
				"types",
				"List all rack layouts",
				"/collection.v1.DeviceCollectionService/ListRackTypes",
				generatedAuthBearer,
				[]cli.Flag{
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.ListRackTypesRequest{}
					return req, nil
				},
				func() proto.Message { return &collectionv1.ListRackTypesResponse{} },
			),
			generatedRequestCommand(
				"zones",
				"List all rack zones",
				"/collection.v1.DeviceCollectionService/ListRackZones",
				generatedAuthBearer,
				[]cli.Flag{
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.ListRackZonesRequest{}
					return req, nil
				},
				func() proto.Message { return &collectionv1.ListRackZonesResponse{} },
			),
		},
	}
}
