// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	poolsv1 "github.com/block/proto-fleet/server/generated/grpc/pools/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

func generatedPoolsCommand() *cli.Command {
	return &cli.Command{
		Name:  "pools",
		Usage: "Manage pools commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"create",
				"Create pool",
				"/pools.v1.PoolsService/CreatePool",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.StringFlag{Name: "pool-name", Usage: "pool name"},
					&cli.StringFlag{Name: "url", Usage: "url"},
					&cli.StringFlag{Name: "username", Usage: "username"},
					&cli.StringFlag{Name: "password", Usage: "password"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &poolsv1.CreatePoolRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if cmd.IsSet("pool-name") || cmd.IsSet("url") || cmd.IsSet("username") || cmd.IsSet("password") {
						req.PoolConfig = &poolsv1.PoolConfig{}
						if cmd.IsSet("pool-name") {
							req.PoolConfig.PoolName = cmd.String("pool-name")
						}
						if cmd.IsSet("url") {
							req.PoolConfig.Url = cmd.String("url")
						}
						if cmd.IsSet("username") {
							req.PoolConfig.Username = cmd.String("username")
						}
						if cmd.IsSet("password") {
							req.PoolConfig.Password = wrapperspb.String(cmd.String("password"))
						}
					}
					return req, nil
				},
				func() proto.Message { return &poolsv1.CreatePoolResponse{} },
			),
			generatedRequestCommand(
				"delete",
				"Delete pool",
				"/pools.v1.PoolsService/DeletePool",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.Int64Flag{Name: "pool-id", Usage: "pool id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &poolsv1.DeletePoolRequest{}
					if cmd.IsSet("pool-id") {
						req.PoolId = cmd.Int64("pool-id")
					}
					return req, nil
				},
				func() proto.Message { return &poolsv1.DeletePoolResponse{} },
			),
			generatedRequestCommand(
				"list",
				"List pools",
				"/pools.v1.PoolsService/ListPools",
				generatedAuthBearer,
				[]cli.Flag{
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &poolsv1.ListPoolsRequest{}
					return req, nil
				},
				func() proto.Message { return &poolsv1.ListPoolsResponse{} },
			),
			generatedRequestCommand(
				"update",
				"Update pool",
				"/pools.v1.PoolsService/UpdatePool",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.Int64Flag{Name: "pool-id", Usage: "pool id"},
					&cli.StringFlag{Name: "pool-name", Usage: "pool name"},
					&cli.StringFlag{Name: "url", Usage: "url"},
					&cli.StringFlag{Name: "username", Usage: "username"},
					&cli.StringFlag{Name: "password", Usage: "password"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &poolsv1.UpdatePoolRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if cmd.IsSet("pool-id") {
						req.PoolId = cmd.Int64("pool-id")
					}
					if cmd.IsSet("pool-name") {
						value := cmd.String("pool-name")
						req.PoolName = &value
					}
					if cmd.IsSet("url") {
						value := cmd.String("url")
						req.Url = &value
					}
					if cmd.IsSet("username") {
						value := cmd.String("username")
						req.Username = &value
					}
					if cmd.IsSet("password") {
						req.Password = wrapperspb.String(cmd.String("password"))
					}
					return req, nil
				},
				func() proto.Message { return &poolsv1.UpdatePoolResponse{} },
			),
			generatedRequestCommand(
				"validate",
				"Validate pool",
				"/pools.v1.PoolsService/ValidatePool",
				generatedAuthBearer,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.StringFlag{Name: "url", Usage: "url"},
					&cli.StringFlag{Name: "username", Usage: "username"},
					&cli.StringFlag{Name: "password", Usage: "password"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &poolsv1.ValidatePoolRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if cmd.IsSet("url") {
						req.Url = cmd.String("url")
					}
					if cmd.IsSet("username") {
						req.Username = cmd.String("username")
					}
					if cmd.IsSet("password") {
						req.Password = wrapperspb.String(cmd.String("password"))
					}
					return req, nil
				},
				func() proto.Message { return &poolsv1.ValidatePoolResponse{} },
			),
		},
	}
}
